name: laava
channels:
    - conda-forge
    - bioconda
    - defaults
dependencies:
    - python>=3.8
    - r-base>=3.6.0
    - biopython
    - pandas
    - parasail-python>=1.3.4
    - pysam
    - pytest
    - r-flextable
    - r-gdtools
    - r-lintr
    - r-rmarkdown
    - r-systemfonts
    - r-tidyverse
    - ruff
