name: 'Setup Environment'
description: 'Setup Python, conda, and system dependencies'
inputs:
  python-version:
    description: 'Python version to use'
    required: true
    default: '3.10'
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
    - name: Install apt packages
      shell: bash
      run: |
        sudo apt-get update \
        && sudo apt-get install -y samtools texlive-latex-extra texlive-latex-recommended \
        && sudo apt-get remove -y fonts-urw-base35 libgs9 libgs9-common libjbig2dec0 poppler-data
    - name: Cache conda
      uses: actions/cache@v4
      env:
        # Increase this value to reset cache if conda_env.yml has not changed
        CACHE_NUMBER: 0
      with:
        path: ~/conda_pkgs_dir
        key:
          ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('conda_env.yml') }}
    - uses: conda-incubator/setup-miniconda@v3
      with:
        activate-environment: laava
        auto-activate-base: false
        auto-update-conda: true
        channel-priority: strict
        environment-file: conda_env.yml
        python-version: ${{ inputs.python-version }}
        use-only-tar-bz2: true  # Required for caching
    - name: Show conda environment
      shell: bash -el {0}
      run: |
        conda info
        conda list
