name: Lint

on: [push, pull_request]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - uses: actions/cache@v4
        env:
          # Increase this value to reset cache if conda_env.yml has not changed
            CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key:
            ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('conda_env.yml') }}
      - uses: conda-incubator/setup-miniconda@v3
        with:
            activate-environment: laava
            auto-activate-base: false
            auto-update-conda: true
            channel-priority: strict
            environment-file: conda_env.yml
            python-version: '3.10'
            use-only-tar-bz2: true  # Required for caching       
      - name: Lint Python ruff
        run: | 
            make lint-python
      - name: Lint R script
        run: |
            make lint-r