name: Lint

on: [push, pull_request]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - uses: chartboost/ruff-action@v1
        with:
          args: 'check --output-format=github'
      - uses: chartboost/ruff-action@v1
        with:
          args: 'format --check'
  lint-r:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lint R script
        run: |
            make lint-r