name: Tests

on:
  push:
    branches:
      - main
    paths-ignore:
      - '*.md'
  pull_request:
    paths-ignore:
      - '*.md'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        # Enable the conda environment via ~/.bashrc and ~/.profile
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-environment
        with:
          python-version: '3.10'
      - name: Lint Python ruff
        run: | 
            make lint-python
      - name: Lint R script
        run: |
            make lint-r

  tests:
    name: Test with Python ${{ matrix.python }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest']
        python: ['3.10', '3.9', '3.8']
    defaults:
      run:
        # Enable the conda environment via ~/.bashrc and ~/.profile
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-environment
        with:
          python-version: ${{ matrix.python }}
      - name: Test script outputs
        run: |
          cd test && make test
