name: Tests

on:
  push:
    branches:
      - main
    paths-ignore:
      - '*.md'
  pull_request:
    paths-ignore:
      - '*.md'

jobs:
  tests:
    name: Test with Python ${{ matrix.python }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest']
        python: ['3.10', '3.9', '3.8']
    defaults:
      run:
        # Enable the conda environment via ~/.bashrc and ~/.profile
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - name: Install apt packages
        run: |
          sudo apt-get update \
          && sudo apt-get install -y samtools texlive-latex-extra texlive-latex-recommended \
          && sudo apt-get remove -y fonts-urw-base35 libgs9 libgs9-common libjbig2dec0 poppler-data
      - name: Cache conda
        uses: actions/cache@v4
        env:
          # Increase this value to reset cache if conda_env.yml has not changed
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key:
            ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('conda_env.yml') }}
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: laava
          auto-activate-base: false
          auto-update-conda: true
          channel-priority: strict
          environment-file: conda_env.yml
          python-version: ${{ matrix.python }}
          use-only-tar-bz2: true  # Required for caching
      - name: Show conda environment
        run: |
          conda info
          conda list
      - name: Lint Python scripts
        run: |
          # Stop the build if there are Python syntax errors or undefined names
          ruff check --isolated --no-cache src/
      - name: Lint R script
        run: |
          Rscript -e 'library(lintr); options(lintr.error_on_lint=TRUE); lint_dir(".", linters=linters_with_tags("correctness"))'
      - name: Test script outputs
        run: |
          cd test && make test
